version: 0.2

env:
  variables:
    region: ap-southeast-2
phases:
  install:
    runtime-versions:
      python: 3.8
    commands:
      - aws --version
      - aws s3 ls
      - pip install pyinstaller
  build:
    commands:
      - pyinstaller.exe ./test.py
